
import type { Department, Class, Student, Staff } from './types';

export const departments: Department[] = [
  { id: 'cse', name: 'CSE' },
  { id: 'ece', name: 'ECE' },
  { id: 'bme', name: 'BME' },
  { id: 'eee', name: 'EEE' },
  { id: 'mech', name: 'MECH' },
  { id: 'mba', name: 'MBA' },
];

export const classes: Class[] = [
  // CSE
  { id: 'cse-2-a', departmentId: 'cse', name: 'II-A' },
  { id: 'cse-2-b', departmentId: 'cse', name: 'II-B' },
  { id: 'cse-3-a', departmentId: 'cse', name: 'III-A' },
  { id: 'cse-3-b', departmentId: 'cse', name: 'III-B' },
  { id: 'cse-4-a', departmentId: 'cse', name: 'IV-A' },
  { id: 'cse-4-b', departmentId: 'cse', name: 'IV-B' },
  // ECE
  { id: 'ece-2', departmentId: 'ece', name: 'II' },
  { id: 'ece-3', departmentId: 'ece', name: 'III' },
  { id: 'ece-4', departmentId: 'ece', name: 'IV' },
  // BME
  { id: 'bme-2', departmentId: 'bme', name: 'II' },
  { id: 'bme-3', departmentId: 'bme', name: 'III' },
  { id: 'bme-4', departmentId: 'bme', name: 'IV' },
  // EEE
  { id: 'eee-2', departmentId: 'eee', name: 'II' },
  { id: 'eee-3', departmentId: 'eee', name: 'III' },
  { id: 'eee-4', departmentId: 'eee', name: 'IV' },
  // MECH
  { id: 'mech-2', departmentId: 'mech', name: 'II' },
  { id: 'mech-3', departmentId: 'mech', name: 'III' },
  { id: 'mech-4', departmentId: 'mech', name: 'IV' },
  // MBA
  { id: 'mba-1', departmentId: 'mba', name: 'I' },
  { id: 'mba-2-a', departmentId: 'mba', name: 'II-A' },
  { id: 'mba-2-b', departmentId: 'mba', name: 'II-B' },
];

export const students: Student[] = [
  // BME II
  { id: 'bme-2-1', name: 'AKSHAYA M', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0051', gender: 'FEMALE' },
  { id: 'bme-2-2', name: 'ARULARASAN M', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0052', gender: 'MALE' },
  { id: 'bme-2-3', name: 'CHARUMATHI P', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0053', gender: 'FEMALE' },
  { id: 'bme-2-4', name: 'DEEPAK M', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0054', gender: 'MALE' },
  { id: 'bme-2-5', name: 'DEEPAK R', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0055', gender: 'MALE' },
  { id: 'bme-2-6', name: 'DEEPALAKSHMI K', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0056', gender: 'FEMALE' },
  { id: 'bme-2-7', name: 'DHARANI S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0057', gender: 'FEMALE' },
  { id: 'bme-2-8', name: 'EGANATHAN R', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0058', gender: 'MALE' },
  { id: 'bme-2-9', name: 'GIRIJA B', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0059', gender: 'FEMALE' },
  { id: 'bme-2-10', name: 'GOBIGA V', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0060', gender: 'FEMALE' },
  { id: 'bme-2-11', name: 'HEMASUDHA R', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0061', gender: 'MALE' },
  { id: 'bme-2-12', name: 'JANANI S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0062', gender: 'FEMALE' },
  { id: 'bme-2-13', name: 'KANISHKA E', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0064', gender: 'FEMALE' },
  { id: 'bme-2-14', name: 'KESAVAN R', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0066', gender: 'MALE' },
  { id: 'bme-2-15', name: 'KIRUTHIKA M', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0067', gender: 'FEMALE' },
  { id: 'bme-2-16', name: 'KISHORE M', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0068', gender: 'MALE' },
  { id: 'bme-2-17', name: 'KUGAN K', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0069', gender: 'MALE' },
  { id: 'bme-2-18', name: 'LEELAVATHI S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0070', gender: 'FEMALE' },
  { id: 'bme-2-19', name: 'MOHAMED SALMAN S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0071', gender: 'MALE' },
  { id: 'bme-2-20', name: 'NOORUL SHIFAYA S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0072', gender: 'FEMALE' },
  { id: 'bme-2-21', name: 'PRASANNA M', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0073', gender: 'MALE' },
  { id: 'bme-2-22', name: 'PRAVEEN A', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0074', gender: 'MALE' },
  { id: 'bme-2-23', name: 'PUGAZHENTHI R', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0075', gender: 'MALE' },
  { id: 'bme-2-24', name: 'RAJESWARI S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0076', gender: 'FEMALE' },
  { id: 'bme-2-25', name: 'ROHITH RAGAV P', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0077', gender: 'MALE' },
  { id: 'bme-2-26', name: 'SABARI NATHAN R', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0078', gender: 'MALE' },
  { id: 'bme-2-27', name: 'SAKTHEESWARI V', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0079', gender: 'FEMALE' },
  { id: 'bme-2-28', name: 'SAVITHA D P', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0080', gender: 'FEMALE' },
  { id: 'bme-2-29', name: 'SAYE PRIYA S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0081', gender: 'FEMALE' },
  { id: 'bme-2-30', name: 'SILAMBARASI S', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0082', gender: 'FEMALE' },
  { id: 'bme-2-31', name: 'SRIRAMPRATHIN D', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0083', gender: 'MALE' },
  { id: 'bme-2-32', name: 'SUBASRI P', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0084', gender: 'FEMALE' },
  { id: 'bme-2-33', name: 'SUHAINA BEGUM A', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0085', gender: 'FEMALE' },
  { id: 'bme-2-34', name: 'SWETHA V', departmentId: 'bme', classId: 'bme-2', registerNo: '24TJ0086', gender: 'FEMALE' },

  // BME III
  { id: 'bme-3-1', name: 'ABINAYA R', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0051', gender: 'FEMALE' },
  { id: 'bme-3-2', name: 'ABINAYASRI S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0052', gender: 'FEMALE' },
  { id: 'bme-3-3', name: 'ABINISHA S A', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0053', gender: 'FEMALE' },
  { id: 'bme-3-4', name: 'AGALYA C', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0054', gender: 'FEMALE' },
  { id: 'bme-3-5', name: 'ARCHANADEVI S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0055', gender: 'FEMALE' },
  { id: 'bme-3-6', name: 'ASHWINI A', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0056', gender: 'FEMALE' },
  { id: 'bme-3-7', name: 'BAVIYAA SRI N', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0058', gender: 'FEMALE' },
  { id: 'bme-3-8', name: 'BHUVANESHWARI . S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0059', gender: 'FEMALE' },
  { id: 'bme-3-9', name: 'CATHRIN STONICA .D', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0060', gender: 'FEMALE' },
  { id: 'bme-3-10', name: 'DEVANIDHIYA . S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0061', gender: 'FEMALE' },
  { id: 'bme-3-11', name: 'DEVIGA V', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0062', gender: 'FEMALE' },
  { id: 'bme-3-12', name: 'DHINESH . B', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0063', gender: 'MALE' },
  { id: 'bme-3-13', name: 'DHINESH KUMAR R', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0064', gender: 'MALE' },
  { id: 'bme-3-14', name: 'EZHILARASAN V', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0065', gender: 'MALE' },
  { id: 'bme-3-15', name: 'FAIZAL RAHMAN M', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0066', gender: 'MALE' },
  { id: 'bme-3-16', name: 'GAYATHRI B', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0067', gender: 'FEMALE' },
  { id: 'bme-3-17', name: 'HARIHARAN S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0068', gender: 'MALE' },
  { id: 'bme-3-18', name: 'HARINI R', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0069', gender: 'FEMALE' },
  { id: 'bme-3-19', name: 'HARIPRIYA I', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0070', gender: 'FEMALE' },
  { id: 'bme-3-20', name: 'HEMAVARSHINI . M', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0071', gender: 'FEMALE' },
  { id: 'bme-3-21', name: 'ILANCHEZHIYAN R', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0072', gender: 'MALE' },
  { id: 'bme-3-22', name: 'JAIRAJ C', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0073', gender: 'MALE' },
  { id: 'bme-3-23', name: 'JANANI R', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0074', gender: 'FEMALE' },
  { id: 'bme-3-24', name: 'JOY CLITUS .A', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0075', gender: 'MALE' },
  { id: 'bme-3-25', name: 'KIRUTHIKA K', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0076', gender: 'FEMALE' },
  { id: 'bme-3-26', name: 'KIRUTHIKA. S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0077', gender: 'FEMALE' },
  { id: 'bme-3-27', name: 'KOUSIGAN M', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0078', gender: 'MALE' },
  { id: 'bme-3-28', name: 'MONICA MERLYNE T', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0079', gender: 'FEMALE' },
  { id: 'bme-3-29', name: 'PRITHIVIRAJ . K', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0080', gender: 'MALE' },
  { id: 'bme-3-30', name: 'PUGAZHENTHI A', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0081', gender: 'FEMALE' },
  { id: 'bme-3-31', name: 'RITHIGA K', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0082', gender: 'FEMALE' },
  { id: 'bme-3-32', name: 'SAKTHIVEL B', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0083', gender: 'MALE' },
  { id: 'bme-3-33', name: 'SAMUNDEESWARI T', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0084', gender: 'FEMALE' },
  { id: 'bme-3-34', name: 'SANGAVI S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0085', gender: 'FEMALE' },
  { id: 'bme-3-35', name: 'SANTHIYA S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0086', gender: 'FEMALE' },
  { id: 'bme-3-36', name: 'SANTHOSH K', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0087', gender: 'MALE' },
  { id: 'bme-3-37', name: 'SHAMSUNDAR S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0088', gender: 'MALE' },
  { id: 'bme-3-38', name: 'SIVAPRAGASAM K', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0089', gender: 'MALE' },
  { id: 'bme-3-39', name: 'SWAPNA S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0090', gender: 'FEMALE' },
  { id: 'bme-3-40', name: 'THARANGINI P', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0091', gender: 'FEMALE' },
  { id: 'bme-3-41', name: 'URMILA U', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0092', gender: 'FEMALE' },
  { id: 'bme-3-42', name: 'VAISHNAVI K', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0093', gender: 'FEMALE' },
  { id: 'bme-3-43', name: 'VIMALRAJ D', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0094', gender: 'MALE' },
  { id: 'bme-3-44', name: 'VISHNUPRIYA S', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0095', gender: 'FEMALE' },
  { id: 'bme-3-45', name: 'YOKESH C', departmentId: 'bme', classId: 'bme-3', registerNo: '23TJ0096', gender: 'MALE' },

  // BME IV
  { id: 'bme-4-1', name: 'ADHITHIYAN T', departmentId: 'bme', classId: 'bme-4', registerNo: '22TE0122', gender: 'MALE' },
  { id: 'bme-4-2', name: 'ABINAYA B', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0052', gender: 'FEMALE' },
  { id: 'bme-4-3', name: 'ABINKUMAR V', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0053', gender: 'MALE' },
  { id: 'bme-4-4', name: 'AFRATHUL BARIAH B', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0054', gender: 'FEMALE' },
  { id: 'bme-4-5', name: 'BABITHA K', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0055', gender: 'FEMALE' },
  { id: 'bme-4-6', name: 'CHARMILA M', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0056', gender: 'FEMALE' },
  { id: 'bme-4-7', name: 'DHARSHINI N', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0057', gender: 'FEMALE' },
  { id: 'bme-4-8', name: 'DURGASRI R', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0058', gender: 'FEMALE' },
  { id: 'bme-4-9', name: 'GURUVIJAY R', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0059', gender: 'MALE' },
  { id: 'bme-4-10', name: 'HARIHARAN K', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0060', gender: 'MALE' },
  { id: 'bme-4-11', name: 'JANANI S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0061', gender: 'FEMALE' },
  { id: 'bme-4-12', name: 'KRISHNAN S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0062', gender: 'MALE' },
  { id: 'bme-4-13', name: 'MONIKA A', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0064', gender: 'FEMALE' },
  { id: 'bme-4-14', name: 'MONISHA M', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0065', gender: 'FEMALE' },
  { id: 'bme-4-15', name: 'MUKESHKANNA M', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0066', gender: 'MALE' },
  { id: 'bme-4-16', name: 'RAGUL P', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0067', gender: 'MALE' },
  { id: 'bme-4-17', name: 'SANGEETHA M', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0068', gender: 'FEMALE' },
  { id: 'bme-4-18', name: 'SANJAI S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0069', gender: 'MALE' },
  { id: 'bme-4-19', name: 'SARAVANAN S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0070', gender: 'MALE' },
  { id: 'bme-4-20', name: 'SHREELESH S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0071', gender: 'MALE' },
  { id: 'bme-4-21', name: 'SWEDHA S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0072', gender: 'FEMALE' },
  { id: 'bme-4-22', name: 'THAGAMITHA J', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0073', gender: 'FEMALE' },
  { id: 'bme-4-23', name: 'UTHAYAKANNAN K', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0074', gender: 'MALE' },
  { id: 'bme-4-24', name: 'VIJAYAKUMAR S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJ0075', gender: 'MALE' },
  { id: 'bme-4-25', name: 'NIVEDHA.S', departmentId: 'bme', classId: 'bme-4', registerNo: '22TJL001', gender: 'FEMALE' },
  { id: 'bme-4-26', name: 'AARTHI.V', departmentId: 'bme', classId: 'bme-4', registerNo: '20TJ0101', gender: 'FEMALE' },

  // ECE II
  { id: 'ece-2-1', name: 'AJAI.G', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0551', gender: 'MALE' },
  { id: 'ece-2-2', name: 'AJAY.M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0552', gender: 'MALE' },
  { id: 'ece-2-3', name: 'ALEX.R', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0553', gender: 'MALE' },
  { id: 'ece-2-4', name: 'ARAVIND. A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0554', gender: 'MALE' },
  { id: 'ece-2-5', name: 'ARAVINDH.V', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0555', gender: 'MALE' },
  { id: 'ece-2-6', name: 'BALAMURUGAN.R', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0556', gender: 'MALE' },
  { id: 'ece-2-7', name: 'DAYALAN.K', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0557', gender: 'MALE' },
  { id: 'ece-2-8', name: 'DEEPAK.M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0558', gender: 'MALE' },
  { id: 'ece-2-9', name: 'DHARSHINI.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0559', gender: 'FEMALE' },
  { id: 'ece-2-10', name: 'DHINESH BHARATHI.A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0560', gender: 'MALE' },
  { id: 'ece-2-11', name: 'DHIVYA.D', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0561', gender: 'FEMALE' },
  { id: 'ece-2-12', name: 'GANESHKUMAR. M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0562', gender: 'MALE' },
  { id: 'ece-2-13', name: 'GIRI. M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0563', gender: 'MALE' },
  { id: 'ece-2-14', name: 'GOWRI.G', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0564', gender: 'FEMALE' },
  { id: 'ece-2-15', name: 'HARISH .A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0565', gender: 'MALE' },
  { id: 'ece-2-16', name: 'HARISHRAJ K', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0566', gender: 'MALE' },
  { id: 'ece-2-17', name: 'JAYASUNDARAPANDIAN.J', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0567', gender: 'MALE' },
  { id: 'ece-2-18', name: 'JOHNSON.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0568', gender: 'MALE' },
  { id: 'ece-2-19', name: 'KADHIR.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0569', gender: 'MALE' },
  { id: 'ece-2-20', name: 'KALAIVANAN. D', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0570', gender: 'MALE' },
  { id: 'ece-2-21', name: 'KARTHIKEYAN .A.P', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0571', gender: 'MALE' },
  { id: 'ece-2-22', name: 'KAVIYA.K', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0572', gender: 'FEMALE' },
  { id: 'ece-2-23', name: 'KISHORE.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0573', gender: 'MALE' },
  { id: 'ece-2-24', name: 'LAKSITHA.A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0574', gender: 'FEMALE' },
  { id: 'ece-2-25', name: 'LOKESH.M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0575', gender: 'MALE' },
  { id: 'ece-2-57', name: 'LOKESH.M.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0576', gender: 'MALE' },
  { id: 'ece-2-26', name: 'MANIKANDAN .A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0577', gender: 'MALE' },
  { id: 'ece-2-27', name: 'MANIKANDAN. S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0578', gender: 'MALE' },
  { id: 'ece-2-28', name: 'MOSHIKA.U', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0579', gender: 'FEMALE' },
  { id: 'ece-2-29', name: 'MOHAMED MOOSA .M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0580', gender: 'MALE' },
  { id: 'ece-2-30', name: 'NIVEDHA.R', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0581', gender: 'FEMALE' },
  { id: 'ece-2-31', name: 'PAVITHRAN.R', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0582', gender: 'MALE' },
  { id: 'ece-2-32', name: 'PRABHA.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0583', gender: 'FEMALE' },
  { id: 'ece-2-33', name: 'PRATHAPAN.G', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0584', gender: 'MALE' },
  { id: 'ece-2-34', name: 'PUGAZHENDHI B', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0585', gender: 'MALE' },
  { id: 'ece-2-35', name: 'RAGAVARSHINI.P', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0586', gender: 'MALE' },
  { id: 'ece-2-36', name: 'RAGHULGANESH. S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0587', gender: 'MALE' },
  { id: 'ece-2-37', name: 'RAJALATCHOUMY.R', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0588', gender: 'FEMALE' },
  { id: 'ece-2-38', name: 'RAMKUMAR. K', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0589', gender: 'MALE' },
  { id: 'ece-2-39', name: 'RATHIMEENA .V', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0590', gender: 'FEMALE' },
  { id: 'ece-2-40', name: 'SAKTHIRAMAN. V', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0591', gender: 'MALE' },
  { id: 'ece-2-41', name: 'SANJEEV PRASATH T', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0592', gender: 'MALE' },
  { id: 'ece-2-42', name: 'SARAN PRIYA .M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0593', gender: 'FEMALE' },
  { id: 'ece-2-43', name: 'SARANRAJ.M', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0594', gender: 'MALE' },
  { id: 'ece-2-44', name: 'SATHISHKUMAR . S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0595', gender: 'MALE' },
  { id: 'ece-2-45', name: 'SHANMUGANATHAN. A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0596', gender: 'MALE' },
  { id: 'ece-2-46', name: 'SHARMILA. P', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0597', gender: 'FEMALE' },
  { id: 'ece-2-47', name: 'SHINAK BAGAM. E', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0598', gender: 'FEMALE' },
  { id: 'ece-2-48', name: 'SIDHARTH. J', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0599', gender: 'MALE' },
  { id: 'ece-2-49', name: 'SIVARAJ.B', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0600', gender: 'MALE' },
  { id: 'ece-2-50', name: 'SUBIKSHA .T', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0601', gender: 'FEMALE' },
  { id: 'ece-2-51', name: 'SURESH.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0602', gender: 'MALE' },
  { id: 'ece-2-52', name: 'SUSHMITHA. A', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0603', gender: 'FEMALE' },
  { id: 'ece-2-53', name: 'VIGNESH. B', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0604', gender: 'MALE' },
  { id: 'ece-2-54', name: 'YASAR ARAFATH. G', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0605', gender: 'MALE' },
  { id: 'ece-2-55', name: 'YOGA PRIYA.P', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0606', gender: 'FEMALE' },
  { id: 'ece-2-56', name: 'YUVASRI.S', departmentId: 'ece', classId: 'ece-2', registerNo: '24TC0607', gender: 'FEMALE' },

  // ECE III
  { id: 'ece-3-1', name: 'AAMINA BEGAM G', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0501', gender: 'FEMALE' },
  { id: 'ece-3-2', name: 'ABIMANYU S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0502', gender: 'MALE' },
  { id: 'ece-3-3', name: 'ACHAYA S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0503', gender: 'FEMALE' },
  { id: 'ece-3-4', name: 'ADHISHESHAN V', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0504', gender: 'MALE' },
  { id: 'ece-3-5', name: 'AMSAVALLI A', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0505', gender: 'FEMALE' },
  { id: 'ece-3-6', name: 'ANANDHY M', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0506', gender: 'FEMALE' },
  { id: 'ece-3-7', name: 'ARUNRAJ R', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0507', gender: 'MALE' },
  { id: 'ece-3-8', name: 'AYYANAR M', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0508', gender: 'MALE' },
  { id: 'ece-3-9', name: 'CHANDAR K', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0509', gender: 'MALE' },
  { id: 'ece-3-10', name: 'DEEPIKA K', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0510', gender: 'FEMALE' },
  { id: 'ece-3-11', name: 'DHAYANITHY V', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0511', gender: 'MALE' },
  { id: 'ece-3-12', name: 'GAYATHRI M', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0512', gender: 'FEMALE' },
  { id: 'ece-3-13', name: 'GOKULAKRISHNAN S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0513', gender: 'MALE' },
  { id: 'ece-3-14', name: 'HEMADARSHINI J', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0514', gender: 'FEMALE' },
  { id: 'ece-3-15', name: 'JAGAN V', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0515', gender: 'MALE' },
  { id: 'ece-3-16', name: 'KAVIARASU S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0516', gender: 'MALE' },
  { id: 'ece-3-17', name: 'KAVIRAJAN L', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0517', gender: 'MALE' },
  { id: 'ece-3-18', name: 'KAVIYA B', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0518', gender: 'FEMALE' },
  { id: 'ece-3-19', name: 'KAVIYA S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0519', gender: 'FEMALE' },
  { id: 'ece-3-20', name: 'KEERTHANA S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0520', gender: 'FEMALE' },
  { id: 'ece-3-21', name: 'LAVANYA N', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0521', gender: 'FEMALE' },
  { id: 'ece-3-22', name: 'MAHESH R', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0522', gender: 'MALE' },
  { id: 'ece-3-23', name: 'MOHAMED YASSIN S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0523', gender: 'MALE' },
  { id: 'ece-3-24', name: 'MOHANRAJ N', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0524', gender: 'MALE' },
  { id: 'ece-3-25', name: 'MONISHA S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0525', gender: 'FEMALE' },
  { id: 'ece-3-26', name: 'NAVEENKUMAR R', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0526', gender: 'MALE' },
  { id: 'ece-3-27', name: 'NIVETHA SHREE M S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0528', gender: 'FEMALE' },
  { id: 'ece-3-28', name: 'PARTHASARATHY B', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0529', gender: 'MALE' },
  { id: 'ece-3-29', name: 'PARTHIBAN S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0530', gender: 'MALE' },
  { id: 'ece-3-30', name: 'PRATIK PANDAY', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0531', gender: 'MALE' },
  { id: 'ece-3-31', name: 'PRAVEENA K', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0532', gender: 'FEMALE' },
  { id: 'ece-3-32', name: 'RAM KUMAR J', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0533', gender: 'MALE' },
  { id: 'ece-3-33', name: 'REGAN R', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0535', gender: 'MALE' },
  { id: 'ece-3-34', name: 'ROHITH E', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0536', gender: 'MALE' },
  { id: 'ece-3-35', name: 'SANJAI D', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0537', gender: 'MALE' },
  { id: 'ece-3-36', name: 'SANJAI M', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0538', gender: 'MALE' },
  { id: 'ece-3-37', name: 'SARTHAJ S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0539', gender: 'FEMALE' },
  { id: 'ece-3-38', name: 'SENTHILKUMARAN E', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0540', gender: 'MALE' },
  { id: 'ece-3-39', name: 'SHALINI M', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0541', gender: 'FEMALE' },
  { id: 'ece-3-40', name: 'SIBANI M', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0542', gender: 'FEMALE' },
  { id: 'ece-3-41', name: 'SIDHARTHAN D', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0543', gender: 'MALE' },
  { id: 'ece-3-42', name: 'SRINIDHI S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0544', gender: 'FEMALE' },
  { id: 'ece-3-43', name: 'STELLA MARY S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0545', gender: 'FEMALE' },
  { id: 'ece-3-44', name: 'SUDHAN P', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0546', gender: 'MALE' },
  { id: 'ece-3-45', name: 'SUJITH S', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0547', gender: 'MALE' },
  { id: 'ece-3-46', name: 'SUJITHA B', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0548', gender: 'FEMALE' },
  { id: 'ece-3-47', name: 'VIGNESH V', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0550', gender: 'MALE' },
  { id: 'ece-3-48', name: 'VIGNESHVARMA V G', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0551', gender: 'MALE' },
  { id: 'ece-3-49', name: 'VIJAYAKRISHNA U', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0552', gender: 'MALE' },
  { id: 'ece-3-50', name: 'VISHNU B', departmentId: 'ece', classId: 'ece-3', registerNo: '23TC0553', gender: 'MALE' },
  { id: 'ece-3-51', name: 'RIYA KERKETTA', departmentId: 'ece', classId: 'ece-3', registerNo: '21TC0269', gender: 'FEMALE' },

  // ECE IV
  { id: 'ece-4-1', name: 'ABUBAKKER SIDDIQUE H', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0451', gender: 'MALE' },
  { id: 'ece-4-2', name: 'AJAI N', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0452', gender: 'MALE' },
  { id: 'ece-4-3', name: 'AKASH M', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0453', gender: 'MALE' },
  { id: 'ece-4-4', name: 'AKASH R', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0454', gender: 'MALE' },
  { id: 'ece-4-5', name: 'DHANUSH KUMAR A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0455', gender: 'MALE' },
  { id: 'ece-4-6', name: 'DHARMA SASTHA L', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0456', gender: 'MALE' },
  { id: 'ece-4-7', name: 'DURGADEVI D', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0457', gender: 'FEMALE' },
  { id: 'ece-4-8', name: 'DURGAPRASATH K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0458', gender: 'MALE' },
  { id: 'ece-4-9', name: 'ELANGO N', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0459', gender: 'MALE' },
  { id: 'ece-4-10', name: 'GOKULNATH A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0460', gender: 'MALE' },
  { id: 'ece-4-11', name: 'GOWTHAM G', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0461', gender: 'MALE' },
  { id: 'ece-4-12', name: 'HAMALEKHA K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0462', gender: 'FEMALE' },
  { id: 'ece-4-13', name: 'HARIHARAN V', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0463', gender: 'MALE' },
  { id: 'ece-4-14', name: 'HARISH K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0464', gender: 'MALE' },
  { id: 'ece-4-15', name: 'HEMA PRADEEP A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0465', gender: 'MALE' },
  { id: 'ece-4-16', name: 'HEMAAMARNATH V', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0466', gender: 'MALE' },
  { id: 'ece-4-17', name: 'ILAMARAN A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0467', gender: 'MALE' },
  { id: 'ece-4-18', name: 'INDIRAJITH K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0468', gender: 'MALE' },
  { id: 'ece-4-19', name: 'JAYASWARNA M', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0470', gender: 'FEMALE' },
  { id: 'ece-4-20', name: 'KARTHIK G', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0471', gender: 'MALE' },
  { id: 'ece-4-21', name: 'KARTHIK R', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0472', gender: 'MALE' },
  { id: 'ece-4-22', name: 'KISHORE KUMAR J', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0474', gender: 'MALE' },
  { id: 'ece-4-23', name: 'KISHORRAJ G', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0475', gender: 'MALE' },
  { id: 'ece-4-24', name: 'LAKSHAYA P', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0476', gender: 'FEMALE' },
  { id: 'ece-4-25', name: 'MANIKANDAN S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0477', gender: 'MALE' },
  { id: 'ece-4-26', name: 'MANJU V', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0478', gender: 'FEMALE' },
  { id: 'ece-4-27', name: 'MARTIN DESOUZA A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0479', gender: 'MALE' },
  { id: 'ece-4-28', name: 'MONISHA S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0480', gender: 'FEMALE' },
  { id: 'ece-4-29', name: 'MUTHULAKSHMI K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0481', gender: 'FEMALE' },
  { id: 'ece-4-30', name: 'MYTHILI V', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0482', gender: 'FEMALE' },
  { id: 'ece-4-31', name: 'NAGAMANI ALIAS VINITHA M', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0483', gender: 'FEMALE' },
  { id: 'ece-4-32', name: 'NIVETHA V', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0486', gender: 'FEMALE' },
  { id: 'ece-4-33', name: 'OM PRAKASH S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0487', gender: 'MALE' },
  { id: 'ece-4-34', name: 'PIRIYADHARSHNI R', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0488', gender: 'FEMALE' },
  { id: 'ece-4-35', name: 'RAMPRASATH C', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0489', gender: 'MALE' },
  { id: 'ece-4-36', name: 'RENUGA S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0490', gender: 'FEMALE' },
  { id: 'ece-4-37', name: 'RUPIKA K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0491', gender: 'FEMALE' },
  { id: 'ece-4-38', name: 'SAMUEL S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0492', gender: 'MALE' },
  { id: 'ece-4-39', name: 'SRINITHY R', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0494', gender: 'FEMALE' },
  { id: 'ece-4-40', name: 'SUVAM DAS S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0495', gender: 'MALE' },
  { id: 'ece-4-41', name: 'SUVETHA V', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0496', gender: 'FEMALE' },
  { id: 'ece-4-42', name: 'THANUJAA S', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0497', gender: 'FEMALE' },
  { id: 'ece-4-43', name: 'THILAKESWAR A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0498', gender: 'MALE' },
  { id: 'ece-4-44', name: 'THIRUMURUGAN K', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0499', gender: 'MALE' },
  { id: 'ece-4-45', name: 'VAISHNAVI D', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0500', gender: 'FEMALE' },
  { id: 'ece-4-46', name: 'VANATHI A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0501', gender: 'FEMALE' },
  { id: 'ece-4-47', name: 'VASIKARAN B', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0502', gender: 'MALE' },
  { id: 'ece-4-48', name: 'VENKATESAN S P C', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0503', gender: 'MALE' },
  { id: 'ece-4-49', name: 'VIJAYARAGAVAN R', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0504', gender: 'MALE' },
  { id: 'ece-4-50', name: 'VIKRAM M', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0505', gender: 'MALE' },
  { id: 'ece-4-51', name: 'VINOTHINI G', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0506', gender: 'FEMALE' },
  { id: 'ece-4-52', name: 'YUVARAJ R', departmentId: 'ece', classId: 'ece-4', registerNo: '22TC0507', gender: 'MALE' },
  { id: 'ece-4-53', name: 'AMAYA PAVITHRAN', departmentId: 'ece', classId: 'ece-4', registerNo: '22TE0124', gender: 'FEMALE' },
  { id: 'ece-4-54', name: 'BHUVANESHWARI C', departmentId: 'ece', classId: 'ece-4', registerNo: '22TE0126', gender: 'FEMALE' },
  { id: 'ece-4-55', name: 'RESHMA A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TE0131', gender: 'FEMALE' },
  { id: 'ece-4-56', name: 'KISHORE M', departmentId: 'ece', classId: 'ece-4', registerNo: '22TE0129', gender: 'MALE' },
  { id: 'ece-4-57', name: 'ABI A', departmentId: 'ece', classId: 'ece-4', registerNo: '22TJ0051', gender: 'FEMALE' },
  { id: 'ece-4-58', name: 'JAYASURIYA P L', departmentId: 'ece', classId: 'ece-4', registerNo: '21TC0258', gender: 'MALE' },
  
  // EEE II
  { id: 'eee-2-1', name: 'JEEVEDHA K', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0151', gender: 'FEMALE' },
  { id: 'eee-2-2', name: 'KAUSTUBH MISHRA', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0152', gender: 'MALE' },
  { id: 'eee-2-3', name: 'KIRANBHAVAN A', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0153', gender: 'MALE' },
  { id: 'eee-2-4', name: 'LOGESWARAN R', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0154', gender: 'MALE' },
  { id: 'eee-2-5', name: 'RAKSHINI K', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0155', gender: 'FEMALE' },
  { id: 'eee-2-6', name: 'SANJAY S', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0156', gender: 'MALE' },
  { id: 'eee-2-7', name: 'SARATHI P', departmentId: 'eee', classId: 'eee-2', registerNo: '24TE0157', gender: 'MALE' },
  { id: 'eee-2-8', name: 'JAISON JOSE M', departmentId: 'eee', classId: 'eee-2', registerNo: 'LATERAL', gender: 'MALE' },
  { id: 'eee-2-9', name: 'SURIYA M', departmentId: 'eee', classId: 'eee-2', registerNo: 'LATERAL', gender: 'MALE' },

  // EEE III
  { id: 'eee-3-1', name: 'ABDUL ALIM R', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0151', gender: 'MALE' },
  { id: 'eee-3-2', name: 'BHUVANESH P', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0152', gender: 'MALE' },
  { id: 'eee-3-3', name: 'DHEEPAK DAYAL RAJ A', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0153', gender: 'MALE' },
  { id: 'eee-3-4', name: 'GOBINATH R', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0154', gender: 'MALE' },
  { id: 'eee-3-5', name: 'PAVISWARAN R', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0155', gender: 'MALE' },
  { id: 'eee-3-6', name: 'PRAVEEN M', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0156', gender: 'MALE' },
  { id: 'eee-3-7', name: 'SABITHA S', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0157', gender: 'FEMALE' },
  { id: 'eee-3-8', name: 'SANJAI V', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0158', gender: 'MALE' },
  { id: 'eee-3-9', name: 'SWETHA P', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0159', gender: 'FEMALE' },
  { id: 'eee-3-10', name: 'TAMIZHVANAN V', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0160', gender: 'MALE' },
  { id: 'eee-3-11', name: 'THARUN K', departmentId: 'eee', classId: 'eee-3', registerNo: '23TE0161', gender: 'MALE' },

  // EEE IV
  { id: 'eee-4-1', name: 'ADHITHIYAN A', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0121', gender: 'MALE' },
  { id: 'eee-4-2', name: 'AMAL PETER A', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0123', gender: 'MALE' },
  { id: 'eee-4-3', name: 'ANITHA J', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0125', gender: 'FEMALE' },
  { id: 'eee-4-4', name: 'ELAMARAN R', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0127', gender: 'MALE' },
  { id: 'eee-4-5', name: 'HARIHARAN S', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0128', gender: 'MALE' },
  { id: 'eee-4-6', name: 'PAVITHRA D', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0130', gender: 'FEMALE' },
  { id: 'eee-4-7', name: 'SYEDSHAUTH M', departmentId: 'eee', classId: 'eee-4', registerNo: '22TE0132', gender: 'MALE' },

  // MECH II
  { id: 'mech-2-1', name: 'GOKUL KRISHNAN. B', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2901', gender: 'MALE' },
  { id: 'mech-2-2', name: 'VINSENT ARNOLD. V', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2902', gender: 'MALE' },
  { id: 'mech-2-3', name: 'RAMANA. T', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2903', gender: 'MALE' },
  { id: 'mech-2-4', name: 'ABINESH. A', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2904', gender: 'MALE' },
  { id: 'mech-2-5', name: 'HARISH. I', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2905', gender: 'MALE' },
  { id: 'mech-2-6', name: 'MEEMNATCHI. K', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2906', gender: 'FEMALE' },
  { id: 'mech-2-7', name: 'DHARANIDHARAN. J', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2907', gender: 'MALE' },
  { id: 'mech-2-8', name: 'SATHIAMURTHI. S', departmentId: 'mech', classId: 'mech-2', registerNo: '24TB2908', gender: 'MALE' },
  
  // MECH III
  { id: 'mech-3-1', name: 'AJITH KUMAR .G', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0201', gender: 'MALE' },
  { id: 'mech-3-2', name: 'GOKULAN . G', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0202', gender: 'MALE' },
  { id: 'mech-3-3', name: 'GUGANESH .B', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0203', gender: 'MALE' },
  { id: 'mech-3-4', name: 'HEMARAJU S', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0204', gender: 'MALE' },
  { id: 'mech-3-5', name: 'JAYAVEERAN . V', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0205', gender: 'MALE' },
  { id: 'mech-3-6', name: 'MOHAMED ISMAYIL .S', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0207', gender: 'MALE' },
  { id: 'mech-3-7', name: 'NITHISHKUMAR .S', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0208', gender: 'MALE' },
  { id: 'mech-3-8', name: 'PRAVEEN . S', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0209', gender: 'MALE' },
  { id: 'mech-3-9', name: 'PUGAZHENDHI . S', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0210', gender: 'MALE' },
  { id: 'mech-3-10', name: 'SANTHOSH . G', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0212', gender: 'MALE' },
  { id: 'mech-3-11', name: 'YUVANARAJA . M', departmentId: 'mech', classId: 'mech-3', registerNo: '23TB0213', gender: 'MALE' },
  { id: 'mech-3-12', name: 'JAGADEESWAR. R', departmentId: 'mech', classId: 'mech-3', registerNo: '23TBL047', gender: 'MALE' },
  { id: 'mech-3-13', name: 'VIJAYAKUMAR . V', departmentId: 'mech', classId: 'mech-3', registerNo: '23TBL049', gender: 'MALE' },
  { id: 'mech-3-14', name: 'MODESHWARAN.R', departmentId: 'mech', classId: 'mech-3', registerNo: '23TBL048', gender: 'MALE' },

  // MECH IV
  { id: 'mech-4-1', name: 'CHANDRU. B', departmentId: 'mech', classId: 'mech-4', registerNo: '22TB0091', gender: 'MALE' },
  { id: 'mech-4-2', name: 'MADHUBALAN. M', departmentId: 'mech', classId: 'mech-4', registerNo: '22TB0094', gender: 'MALE' },
  { id: 'mech-4-3', name: 'RAMKUMAR. A', departmentId: 'mech', classId: 'mech-4', registerNo: '22TB0096', gender: 'MALE' },
  { id: 'mech-4-4', name: 'SAURESH REDDY. S', departmentId: 'mech', classId: 'mech-4', registerNo: '22TB0097', gender: 'MALE' },
  { id: 'mech-4-5', name: 'DUBASH. M', departmentId: 'mech', classId: 'mech-4', registerNo: '22TB0099', gender: 'MALE' },
  { id: 'mech-4-6', name: 'ABDUL BASITH. A', departmentId: 'mech', classId: 'mech-4', registerNo: '22TBL075', gender: 'MALE' },
  { id: 'mech-4-7', name: 'MOHAMAD AHAMAED. J', departmentId: 'mech', classId: 'mech-4', registerNo: '22TBL076', gender: 'MALE' },
  { id: 'mech-4-8', name: 'JAGAN. K', departmentId: 'mech', classId: 'mech-4', registerNo: '22TC0469', gender: 'MALE' },
  // MBA II-A
  { id: 'mba-2a-1', name: 'ANISH JESTINE.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-2', name: 'ASHA.R', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-3', name: 'ATCHAYA.N', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-4', name: 'BABU.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-5', name: 'DHANUSH.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-6', name: 'DHIVIPRIYA.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-7', name: 'DHIVYA.V', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-8', name: 'DINESH.K', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-9', name: 'GOKUL DASS.K', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-10', name: 'GURUSANGARI.K', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-11', name: 'HAAMIDHULLAH.N', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-12', name: 'HARIHAREN.H', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-13', name: 'ISHA.R', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-14', name: 'ISHWARAYA.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-15', name: 'JANARTHANAN.T', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-16', name: 'JEEVITHA.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-17', name: 'JOTHI.B', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-18', name: 'KAMALESHWARAN.A', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-19', name: 'KAMESH.A', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-20', name: 'KARTHIKEYAN.B', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-21', name: 'KEERTHANA.T', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-22', name: 'KEMPU MAHALASHMI.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-23', name: 'KIRUBAGARAN.T', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-24', name: 'KIRUTHIGA.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-25', name: 'KIRUTHIGAA.P', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-26', name: 'KIRUTHIGHA.A', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-27', name: 'LOGESH.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-28', name: 'MALINI.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-29', name: 'MANOJ.A', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-30', name: 'MONISHA.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-31', name: 'NABIYA.V', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-32', name: 'PAVITHRA.E', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-33', name: 'PRAVIN KUMAR.K', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-34', name: 'PREETHIKA.K', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-35', name: 'SANJAI.P', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-36', name: 'SIVARAMAN.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-37', name: 'SIVASRI.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-38', name: 'SOUNDERIYA.N', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-39', name: 'SOWNDHARYA.R', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-40', name: 'SWATHI.R', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-41', name: 'SWEDHA.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-42', name: 'THAIYUBA.S', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-43', name: 'UMASHANKAR.A', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-44', name: 'VARNALAKSHMI.M', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2a-45', name: 'VASANTHA KOUMAAR.V', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-46', name: 'VASU.D', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },
  { id: 'mba-2a-47', name: 'VIMAL.G', departmentId: 'mba', classId: 'mba-2-a', registerNo: '', gender: 'MALE' },

  // MBA II-B
  { id: 'mba-2b-1', name: 'AATHI.V', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-2', name: 'ARTHI.V', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-3', name: 'ARUN PRASAD.T', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-4', name: 'AVINASH.M', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-5', name: 'AYYANAR.A', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-6', name: 'BALAJI.R', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-7', name: 'BHUVANESH.A', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-8', name: 'CLAUDIN.L', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-9', name: 'DHIVYA DHARSHINI.E', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-10', name: 'DHIVYA .M', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-11', name: 'GAYATHRI.M', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-12', name: 'HEMASRI.T', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-13', name: 'JAYASRI.P', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-14', name: 'KAMESHWARAN.J', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-15', name: 'KISHORE.N', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-16', name: 'KISHOTH KUMAR.S', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-17', name: 'LOURDHU SOWMIYA.A', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-18', name: 'MANI MARAN.M', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-19', name: 'MOHAMED INAMUL HASAN.A', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-20', name: 'MOHAMED JUBEIR', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-21', name: 'MYTHILI.R', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-22', name: 'NAVANITHAKRISHNAN.P', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-23', name: 'NETHAJI.B', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-24', name: 'PARASURAMAN', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-25', name: 'PRADEEP.V', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-26', name: 'PREETHIGA.D', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-27', name: 'PREMADAS.S', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-28', name: 'RAGUL.N', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-29', name: 'RAJESH.M', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-30', name: 'SHIVANI.K', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-31', name: 'SIVA.S', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-32', name: 'SIVARANJINI.S', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-33', name: 'SOWMIYA.A', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-34', name: 'SOWMIYA.G', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-35', name: 'SRINIVASAN.R', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-36', name: 'SURESH.E', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-37', name: 'SUSHMITHA.M', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-38', name: 'SWADHI.S', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-39', name: 'THANGAMALAR.K', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-40', name: 'THILAGAVATHI', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-41', name: 'VAITHEESWARI', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-42', name: 'VIGNESH KUMAR', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'MALE' },
  { id: 'mba-2b-43', name: 'YOUVARANI', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-44', name: 'UMAMAHESWARI', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
  { id: 'mba-2b-45', name: 'VAISHNAVI .K', departmentId: 'mba', classId: 'mba-2-b', registerNo: '', gender: 'FEMALE' },
];



    


    

    






