import type { Department, Class, Student, Staff } from './types';

export const departments: Department[] = [
  { id: 'cse', name: 'CSE' },
  { id: 'ece', name: 'ECE' },
  { id: 'bme', name: 'BME' },
  { id: 'eee', name: 'EEE' },
  { id: 'mech', name: 'MECH' },
  { id: 'mba', name: 'MBA' },
];

export const classes: Class[] = [
  // CSE
  { id: 'cse-2a', departmentId: 'cse', name: 'II-A' },
  { id: 'cse-2b', departmentId: 'cse', name: 'II-B' },
  { id: 'cse-3a', departmentId: 'cse', name: 'III-A' },
  { id: 'cse-3b', departmentId: 'cse', name: 'III-B' },
  { id: 'cse-4a', departmentId: 'cse', name: 'IV-A' },
  { id: 'cse-4b', departmentId: 'cse', name: 'IV-B' },
  // ECE
  { id: 'ece-2', departmentId: 'ece', name: 'II' },
  { id: 'ece-3', departmentId: 'ece', name: 'III' },
  { id: 'ece-4', departmentId: 'ece', name: 'IV' },
  // BME
  { id: 'bme-2', departmentId: 'bme', name: 'II' },
  { id: 'bme-3', departmentId: 'bme', name: 'III' },
  { id: 'bme-4', departmentId: 'bme', name: 'IV' },
  // EEE
  { id: 'eee-2', departmentId: 'eee', name: 'II' },
  { id: 'eee-3', departmentId: 'eee', name: 'III' },
  { id: 'eee-4', departmentId: 'eee', name: 'IV' },
  // MECH
  { id: 'mech-2', departmentId: 'mech', name: 'II' },
  { id: 'mech-3', departmentId: 'mech', name: 'III' },
  { id: 'mech-4', departmentId: 'mech', name: 'IV' },
  // MBA
  { id: 'mba-1', departmentId: 'mba', name: 'I' },
  { id: 'mba-2', departmentId: 'mba', name: 'II' },
];

export const students: Student[] = [
  { id: 'cse-4a-1', name: 'AKASH. A', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-2', name: 'AKASH.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-3', name: 'ANANDHU.PS', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-4', name: 'DHINESH KUMAR.C', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-5', name: 'DHIVYA. S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-6', name: 'GANESH.E', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-7', name: 'GAYATHRI. S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-8', name: 'GUHAN.B', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-9', name: 'GUNAAL.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-10', name: 'GURUPRASATH.G', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-11', name: 'HARIHARAN.A', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-12', name: 'JAGAN.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-13', name: 'JAGANSUNDAR.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-14', name: 'JAI KRISHNAN. S. R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-15', name: 'JAYASRI N', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-16', name: 'JAYAVEL.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-17', name: 'KARTHIKEYAN.L', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-18', name: 'KAVITHEESH KUMAR.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-19', name: 'KAVYA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-20', name: 'KEERTHANA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-21', name: 'KOWSHIK.A', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-22', name: 'LOGESHWARAN.K', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-23', name: 'MOHANAKRISHNAN.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-24', name: 'MOHANKUMAR.E', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-25', name: 'NAJWA.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-26', name: 'PRADEEPAN.D', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-27', name: 'PRAVIN.L', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-28', name: 'PRIYA.P', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-29', name: 'RAKSHANA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-30', name: 'RAMYA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-31', name: 'SABARISH.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-32', name: 'SANDHIYA.H', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-33', name: 'SANDHIYA.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-34', name: 'SANGEETHA.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-35', name: 'SARATH. S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-36', name: 'SEETHALAKSHMI.J', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-37', name: 'SRI RAM.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-38', name: 'SUVALAKSHMI.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-39', name: 'THAMIZHARASU.J', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-40', name: 'VIGNESHWARAN.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-41', name: 'VIJAYARAGAVAN.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-42', name: 'VIJAYASANKAR. P', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-43', name: 'VISWANATHAN.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4b-1', name: 'ABINESH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-2', name: 'AKASHRAJ. K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-3', name: 'ANISH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-4', name: 'BARATH.E', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-5', name: 'BENEDIQT HEINRICH .W', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-6', name: 'BHUVANESH.V', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-7', name: 'CHODE PRAVEEN KUMAR', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-8', name: 'DEEPA S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-9', name: 'DHEERAJ A.P', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-10', name: 'DHIVYA PRIYA.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-11', name: 'GIRIDHARAN.N', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-12', name: 'GIRIVASAN.D', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-13', name: 'GOKULAKRISHNAN.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-14', name: 'HARIKRISHNAN.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-15', name: 'HARSHITH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-16', name: 'JANANI.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-17', name: 'JAYAPRAKASH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-18', name: 'JEEVA.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-19', name: 'KANNAN.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-20', name: 'KAVIYA.P', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-21', name: 'KESAVARAMAN.N', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-22', name: 'KRISHNA KUMAR.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-23', name: 'LOUBNA.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-24', name: 'MADHAVAN.B', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-25', name: 'MANOJA.T', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-26', name: 'MARUTHAVEL.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-27', name: 'MOHAMED BARITH.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-28', name: 'MUGUNDARAM.P', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-29', name: 'NANDHINI SRI.V', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-30', name: 'PRADEEP.A', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-31', name: 'SAKTHIDASAN.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-32', name: 'SAKTHIGURUVARAN.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-33', name: 'SANGAVI.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-34', name: 'SANGEETHA.V', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-35', name: 'SANTHOSH.R', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-36', name: 'SASIKALA.R', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-37', name: 'SATYAM KUMAR.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-38', name: 'SURENDHAR.G', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-39', name: 'SWETHA .L', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-40', name: 'THIRUKUMARAN. S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-41', name: 'VASANTHAN.E', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-42', name: 'VITHIYA.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-43', name: 'YOGESH.H', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-44', name: 'YUVASRI.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-2a-1', name: 'MOHAMED IBRAHIM', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-2', name: 'ABDUL HAFIL A', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-3', name: 'ABINAYA G', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-4', name: 'AJAI I', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-5', name: 'AKSHAYA C', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-6', name: 'BHAVA DHARSHNI S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-7', name: 'BUVANESH M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-8', name: 'CATHERINE J', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-9', name: 'CHARU A S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-10', name: 'DHARSHINI M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-11', name: 'DHIVYADHARSHINI R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-12', name: 'DHIVYADHARSHINI S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-13', name: 'DIVYESH M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-14', name: 'ENIYA VARSHAN S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-15', name: 'GOBINATH R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-16', name: 'GOPIKA C', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-17', name: 'GOWTHAM M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-18', name: 'HARINI P', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-19', name: 'HARIPRASATH S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-20', name: 'INIYAN S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-21', name: 'JAMES DARWIN A', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-22', name: 'JHONCY V R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-23', name: 'KABILAN S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-24', name: 'KAMALI K', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-25', name: 'KARTHIVASAN D', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-26', name: 'KISHORE C', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-27', name: 'LAVANYA A', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-28', name: 'MEENA S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-29', name: 'NESIKA P', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-30', name: 'NETHRA P', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-31', name: 'NIRMAL N', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-32', name: 'NIVETHA S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-33', name: 'POOJA T', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-34', name: 'PRAGATHI K', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-35', name: 'PRIYADHARSHINI A', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-36', name: 'PRIYANKA S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-37', name: 'PUGAZHENTHI K', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-38', name: 'RAKESH S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-39', name: 'RAKSHANA R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-40', name: 'SADHANA A', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-41', name: 'SAKKEENA BEGAM T', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-42', name: 'SAKTHIVEL R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-43', name: 'SATHISHKUMAR S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-44', name: 'SHAHARA BANU S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-45', name: 'SHAKSHITHA M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-46', name: 'SHANMUGA PRIYA S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-47', name: 'SOMESHWAR M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-48', name: 'SOUNTHARYA S R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-49', name: 'STEPHEN ANTONY S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-50', name: 'SURENDAR V', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-51', name: 'THILAGAVATHI I', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-52', name: 'VAISHALI I', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-53', name: 'VAISHNAVI N', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-54', name: 'VILASINI R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-55', name: 'YESHUA R', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-56', name: 'YOGAPRIYA V', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-57', name: 'YUKESSH M', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-58', name: 'YUVAPRASAD S', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-59', name: 'ZAINUB I', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2a-60', name: 'BALAMANI P', departmentId: 'cse', classId: 'cse-2a' },
  { id: 'cse-2b-1', name: 'AFRINE S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-2', name: 'AMIRTHARAJ D', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-3', name: 'ATHISESHAN V', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-4', name: 'CHANDHRU M', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-5', name: 'DEEPIKA I', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-6', name: 'DHANA SRI K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-7', name: 'DHARANI PRIYA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-8', name: 'DHINAGAR S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-9', name: 'DINESHKUMAR S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-10', name: 'DIVIYADHARSHINI B', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-11', name: 'FELCINA P', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-12', name: 'GANESH C', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-13', name: 'GOKULAKRISHNAN R', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-14', name: 'GOPINATH T', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-15', name: 'GUHAN M', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-16', name: 'HARISH G', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-17', name: 'HARISH KUMAR K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-18', name: 'HEMAVATHY S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-19', name: 'JAYANTH KARPAGESWAR R', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-20', name: 'KIRUTHIKA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-21', name: 'MALIKSHA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-22', name: 'MANGALAKSHMY M', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-23', name: 'MATHIVANAN V', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-24', name: 'MOHAMED ITHRIS A', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-25', name: 'MONISH K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-26', name: 'NAKKUL R', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-27', name: 'NARKIS BANU D', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-28', name: 'NAVEEN C', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-29', name: 'NIVEDHA K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-30', name: 'PRADHOSHWARAN V K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-31', name: 'PRAKASHIDHA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-32', name: 'PRASANNA K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-33', name: 'PRASHANTHI S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-34', name: 'PRIYADHARSHINI S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-35', name: 'PRIYANKA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-36', name: 'PRIYAVARSAN P', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-37', name: 'RAKESH N', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-38', name: 'RITHIKA K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-39', name: 'SAHANATH FARVEEN R', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-40', name: 'SANJAY S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-41', name: 'SHADHANA NEERTHIKA K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-42', name: 'SHAFANA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-43', name: 'SHARMY B', departmentId: 'cse', classid: 'cse-2b' },
  { id: 'cse-2b-44', name: 'SOMAYA RAMYA M', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-45', name: 'SREE KRISHNAN I', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-46', name: 'SRIVIDHYA THIRUSANGU', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-47', name: 'SUNILKUMAR A', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-48', name: 'SUSI K', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-49', name: 'SUSINDRAN R', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-50', name: 'TANZEELA SULTANA A', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-51', name: 'VAISHNAVI C', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-52', name: 'VAISHNAVI R', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-53', name: 'VIJAYALAKSHMI S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-54', name: 'VIJAYALAKSHMI S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-55', name: 'VISHALINI P', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-56', name: 'YAGAJANANI P', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-57', name: 'YAMIKHA S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-58', name: 'YOGAPRABU V', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-59', name: 'YOGESH C', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-2b-60', name: 'YOGESHWARI S', departmentId: 'cse', classId: 'cse-2b' },
  { id: 'cse-3a-1', name: 'ABINAYA . V', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-2', name: 'ANGELIN JELIS S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-3', name: 'ARISHKUMAR . K', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-4', name: 'ASHWIN . C', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-5', name: 'ASWIN T', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-6', name: 'ATCHAYA . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-7', name: 'DANUSHKUMAR . K', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-8', name: 'DEEPALAKSHMI . G', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-9', name: 'DEVASRI . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-10', name: 'DHARSHANI . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-11', name: 'FAIZAL MOHAMED . P', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-12', name: 'GANESAN . K', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-13', name: 'HARIHARAN . A', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-14', name: 'HARIKRISHNAN . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-15', name: 'HARISHRAJ . V', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-16', name: 'HEMACHANDRAN . G', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-17', name: 'JANITHAA K R', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-18', name: 'JASRA FARVEEN . J', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-19', name: 'JEEVARAAJAN S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-20', name: 'KAMARAJ . M', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-21', name: 'KRISHNA . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-22', name: 'MADHAN . R', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-23', name: 'MAHESH V', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-24', name: 'MANOJ . V', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-25', name: 'MOHAMMED AAQIL . M', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-26', name: 'NAMACHIVAYAM . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-27', name: 'NANDHA KUMAR . B', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-28', name: 'PUSHPARAJ . E', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-29', name: 'RAGUL .A', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-30', name: 'RAMA . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-31', name: 'RANJITH . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-32', name: 'SABREEN . S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-33', name: 'SANIYASRI . J', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-34', name: 'SATHISH . K', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-35', name: 'SATHISH . M', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-36', name: 'SOWKANTHINI . Y', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-37', name: 'SRIVARDHINI .D', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-38', name: 'THULASIMANI . V', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-39', name: 'VIGNESHWARAN V', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-40', name: 'VISHWA . B. R', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-41', name: 'VITHYASAKAR S', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3a-42', name: 'YUVASREE . P', departmentId: 'cse', classId: 'cse-3a' },
  { id: 'cse-3b-1', name: 'AARTHI .A', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-2', name: 'ABARNA  .S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-3', name: 'ABDUL RAHMAN . A', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-4', name: 'ANBARASI . M', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-5', name: 'ANISHA . V', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-6', name: 'BHUVANESHWARAN A', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-7', name: 'DEEPIKA . S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-8', name: 'DHANUSH . V', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-9', name: 'DHARSHINI . S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-10', name: 'DULASI KRISHNA . P', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-11', name: 'GANESH . P', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-12', name: 'GOKUL . S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-13', name: 'HARINI G', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-14', name: 'HARISHKUMAR . R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-15', name: 'JAYA SRINIVASAN . A', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-16', name: 'JEEVITHA . E', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-17', name: 'KALAIVANAN . L', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-18', name: 'KARTHIKEYAN . R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-19', name: 'KESAVAN . M', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-20', name: 'KIROUBAKARAN . V', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-21', name: 'MADHAN.R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-22', name: 'MAHALAKSHMI . A', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-23', name: 'MOHAMED ASIF . M', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-24', name: 'MOHAMED THASLEEM . S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-25', name: 'MUCKTHAR AHAMED . R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-26', name: 'NIKILESHYOGAN . G', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-27', name: 'PADHRINATH . G', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-28', name: 'PARTHASARATHI . S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-29', name: 'PAVITHRA . K', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-30', name: 'PRAKASHRAJ . S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-31', name: 'RENUGA . R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-32', name: 'ROSHEKAA R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-33', name: 'SATHYA J', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-34', name: 'SENTHAMIZH S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-35', name: 'SHALINI . C', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-36', name: 'SHARAN SHANTH . R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-37', name: 'SIVARANJANI K', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-38', name: 'SIVASANKAR . A', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-39', name: 'SRIRAM I', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-40', name: 'SWETHA . R', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-41', name: 'VIJAYAVEL .R. S', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-42', name: 'YOGESH . M', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'cse-3b-43', name: 'YUVASREE . G', departmentId: 'cse', classId: 'cse-3b' },
  { id: 'bme-2-1', name: 'AKSHAYA M', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-2', name: 'ARULARASAN M', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-3', name: 'CHARUMATHI P', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-4', name: 'DEEPAK M', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-5', name: 'DEEPAK R', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-6', name: 'DEEPALAKSHMI K', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-7', name: 'DHARANI S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-8', name: 'EGANATHAN R', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-9', name: 'GIRIJA B', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-10', name: 'GOBIGA V', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-11', name: 'HEMASUDHA R', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-12', name: 'JANANI S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-13', name: 'KANISHKA E', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-14', name: 'KESAVAN R', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-15', name: 'KIRUTHIKA M', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-16', name: 'KISHORE M', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-17', name: 'KUGAN K', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-18', name: 'LEELAVATHI S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-19', name: 'MOHAMED SALMAN S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-20', name: 'NOORUL SHIFAYA S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-21', name: 'PRASANNA M', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-22', name: 'PRAVEEN A', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-23', name: 'PUGAZHENTHI R', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-24', name: 'RAJESWARI S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-25', name: 'ROHITH RAGAV P', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-26', name: 'SABARI NATHAN R', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-27', name: 'SAKTHEESWARI V', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-28', name: 'SAVITHA D P', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-29', name: 'SAYE PRIYA S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-30', name: 'SILAMBARASI S', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-31', name: 'SRIRAMPRATHIN D', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-32', name: 'SUBASRI P', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-33', name: 'SUHAINA BEGUM A', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-2-34', name: 'SWETHA V', departmentId: 'bme', classId: 'bme-2' },
  { id: 'bme-3-1', name: 'ABINAYA R', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-2', name: 'ABINAYASRI S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-3', name: 'ABINISHA S A', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-4', name: 'AGALYA C', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-5', name: 'ARCHANADEVI S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-6', name: 'ASHWINI A', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-7', name: 'BAVIYAA SRI N', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-8', name: 'BHUVANESHWARI . S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-9', name: 'CATHRIN STONICA .D', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-10', name: 'DEVANIDHIYA . S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-11', name: 'DEVIGA V', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-12', name: 'DHINESH . B', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-13', name: 'DHINESH KUMAR R', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-14', name: 'EZHILARASAN V', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-15', name: 'FAIZAL RAHMAN M', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-16', name: 'GAYATHRI B', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-17', name: 'HARIHARAN S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-18', name: 'HARINI R', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-19', name: 'HARIPRIYA I', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-20', name: 'HEMAVARSHINI . M', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-21', name: 'ILANCHEZHIYAN R', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-22', name: 'JAIRAJ C', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-23', name: 'JANANI R', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-24', name: 'JOY CLITUS .A', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-25', name: 'KIRUTHIKA K', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-26', name: 'KIRUTHIKA. S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-27', name: 'KOUSIGAN M', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-28', name: 'MONICA MERLYNE T', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-29', name: 'PRITHIVIRAJ . K', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-30', name: 'PUGAZHENTHI A', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-31', name: 'RITHIGA K', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-32', name: 'SAKTHIVEL B', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-33', name: 'SAMUNDEESWARI T', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-34', name: 'SANGAVI S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-35', name: 'SANTHIYA S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-36', name: 'SANTHOSH K', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-37', name: 'SHAMSUNDAR S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-38', name: 'SIVAPRAGASAM K', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-39', name: 'SWAPNA S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-40', name: 'THARANGINI P', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-41', name: 'URMILA U', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-42', name: 'VAISHNAVI K', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-43', name: 'VIMALRAJ D', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-44', name: 'VISHNUPRIYA S', departmentId: 'bme', classId: 'bme-3' },
  { id: 'bme-3-45', name: 'YOKESH C', departmentId: 'bme', classId: 'bme-3' },
];
