import type { Department, Class, Student, Staff } from './types';

export const departments: Department[] = [
  { id: 'cse', name: 'CSE' },
  { id: 'ece', name: 'ECE' },
  { id: 'bme', name: 'BME' },
  { id: 'eee', name: 'EEE' },
  { id: 'mech', name: 'MECH' },
  { id: 'mba', name: 'MBA' },
];

export const classes: Class[] = [
  // CSE
  { id: 'cse-2a', departmentId: 'cse', name: 'II-A' },
  { id: 'cse-2b', departmentId: 'cse', name: 'II-B' },
  { id: 'cse-3a', departmentId: 'cse', name: 'III-A' },
  { id: 'cse-3b', departmentId: 'cse', name: 'III-B' },
  { id: 'cse-4a', departmentId: 'cse', name: 'IV-A' },
  { id: 'cse-4b', departmentId: 'cse', name: 'IV-B' },
  // ECE
  { id: 'ece-2', departmentId: 'ece', name: 'II' },
  { id: 'ece-3', departmentId: 'ece', name: 'III' },
  { id: 'ece-4', departmentId: 'ece', name: 'IV' },
  // BME
  { id: 'bme-2', departmentId: 'bme', name: 'II' },
  { id: 'bme-3', departmentId: 'bme', name: 'III' },
  { id: 'bme-4', departmentId: 'bme', name: 'IV' },
  // EEE
  { id: 'eee-2', departmentId: 'eee', name: 'II' },
  { id: 'eee-3', departmentId: 'eee', name: 'III' },
  { id: 'eee-4', departmentId: 'eee', name: 'IV' },
  // MECH
  { id: 'mech-2', departmentId: 'mech', name: 'II' },
  { id: 'mech-3', departmentId: 'mech', name: 'III' },
  { id: 'mech-4', departmentId: 'mech', name: 'IV' },
  // MBA
  { id: 'mba-1', departmentId: 'mba', name: 'I' },
  { id: 'mba-2', departmentId: 'mba', name: 'II' },
];

export const students: Student[] = [
  { id: 'cse-4a-1', name: 'AKASH. A', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-2', name: 'AKASH.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-3', name: 'ANANDHU.PS', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-4', name: 'DHINESH KUMAR.C', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-5', name: 'DHIVYA. S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-6', name: 'GANESH.E', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-7', name: 'GAYATHRI. S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-8', name: 'GUHAN.B', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-9', name: 'GUNAAL.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-10', name: 'GURUPRASATH.G', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-11', name: 'HARIHARAN.A', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-12', name: 'JAGAN.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-13', name: 'JAGANSUNDAR.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-14', name: 'JAI KRISHNAN. S. R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-15', name: 'JAYASRI N', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-16', name: 'JAYAVEL.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-17', name: 'KARTHIKEYAN.L', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-18', name: 'KAVITHEESH KUMAR.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-19', name: 'KAVYA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-20', name: 'KEERTHANA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-21', name: 'KOWSHIK.A', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-22', name: 'LOGESHWARAN.K', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-23', name: 'MOHANAKRISHNAN.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-24', name: 'MOHANKUMAR.E', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-25', name: 'NAJWA.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-26', name: 'PRADEEPAN.D', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-27', name: 'PRAVIN.L', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-28', name: 'PRIYA.P', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-29', name: 'RAKSHANA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-30', name: 'RAMYA.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-31', name: 'SABARISH.S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-32', name: 'SANDHIYA.H', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-33', name: 'SANDHIYA.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-34', name: 'SANGEETHA.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-35', name: 'SARATH. S', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-36', name: 'SEETHALAKSHMI.J', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-37', name: 'SRI RAM.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-38', name: 'SUVALAKSHMI.M', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-39', name: 'THAMIZHARASU.J', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-40', name: 'VIGNESHWARAN.R', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-41', name: 'VIJAYARAGAVAN.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-42', name: 'VIJAYASANKAR. P', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4a-43', name: 'VISWANATHAN.V', departmentId: 'cse', classId: 'cse-4a' },
  { id: 'cse-4b-1', name: 'ABINESH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-2', name: 'AKASHRAJ. K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-3', name: 'ANISH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-4', name: 'BARATH.E', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-5', name: 'BENEDIQT HEINRICH .W', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-6', name: 'BHUVANESH.V', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-7', name: 'CHODE PRAVEEN KUMAR', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-8', name: 'DEEPA S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-9', name: 'DHEERAJ A.P', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-10', name: 'DHIVYA PRIYA.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-11', name: 'GIRIDHARAN.N', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-12', name: 'GIRIVASAN.D', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-13', name: 'GOKULAKRISHNAN.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-14', name: 'HARIKRISHNAN.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-15', name: 'HARSHITH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-16', name: 'JANANI.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-17', name: 'JAYAPRAKASH.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-18', name: 'JEEVA.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-19', name: 'KANNAN.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-20', name: 'KAVIYA.P', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-21', name: 'KESAVARAMAN.N', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-22', name: 'KRISHNA KUMAR.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-23', name: 'LOUBNA.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-24', name: 'MADHAVAN.B', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-25', name: 'MANOJA.T', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-26', name: 'MARUTHAVEL.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-27', name: 'MOHAMED BARITH.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-28', name: 'MUGUNDARAM.P', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-29', name: 'NANDHINI SRI.V', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-30', name: 'PRADEEP.A', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-31', name: 'SAKTHIDASAN.S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-32', name: 'SAKTHIGURUVARAN.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-33', name: 'SANGAVI.K', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-34', name: 'SANGEETHA.V', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-35', name: 'SANTHOSH.R', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-36', name: 'SASIKALA.R', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-37', name: 'SATYAM KUMAR.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-38', name: 'SURENDHAR.G', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-39', name: 'SWETHA .L', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-40', name: 'THIRUKUMARAN. S', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-41', name: 'VASANTHAN.E', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-42', name: 'VITHIYA.M', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-43', name: 'YOGESH.H', departmentId: 'cse', classId: 'cse-4b' },
  { id: 'cse-4b-44', name: 'YUVASRI.S', departmentId: 'cse', classId: 'cse-4b' },
];

export const mockStaff: Staff = {
  id: 'staff1',
  name: 'Admin Staff',
  email: 'admin@svcet.com',
};
